name: Extract ZIP File

on: push
# You can adjust the event that triggers the workflow, like `pull_request`, `schedule`, etc.

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install unzip package
      run: sudo apt-get install unzip -y

    - name: Extract ZIP file
      run: unzip a.zip -d extracted_files
